# runnerdeployment.yaml
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: spring-boot-runner
spec:
  replicas: 2
  template:
    spec:
      repository: haithamshahin333/spring-boot-rest-api
      image: acr5r7qx6743t7ly.azurecr.io/custom-gh-runner
      labels:
        - spring-boot-runner
        - custom-image
        - az-cli