# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build Artifact and Container Image

on:
  push:
    branches:
    - main
    - release/*

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'microsoft'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build and Test with Maven
      run: mvn -B package --file pom.xml

    - name: Publish to GitHub Packages Apache Maven
      run: mvn deploy -s $GITHUB_WORKSPACE/settings.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}
        
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        login-server: acrhsdemodevops.azurecr.io

    - name: Docker Build and Push to ACR
      run: |
        docker build . -t acrhsdemodevops.azurecr.io/restapi:${{ github.sha }}
        docker push acrhsdemodevops.azurecr.io/restapi:${{ github.sha }}
        
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: azure/setup-kubectl@v2.0

      # Set the target AKS cluster.
    - uses: Azure/aks-set-context@v1
      with:
        creds: "${{ secrets.AZURE_SP_CREDS }}"
        cluster-name: aks-test-devops-poc
        resource-group: aks-devsecops

    - uses: azure/k8s-bake@v2
      with:
        renderEngine: "helm"
        helmChart: "./spring-boot-app/"
        overrideFiles: "./spring-boot-app/values.yaml"
        overrides: |
          replicaCount:2
        helm-version: "latest"
      id: bake
      
    - name: Validate created manifest ${{ matrix.os }}
      uses: Azure/k8s-lint@v1
      with:
        manifests: ${{ steps.bake.outputs.manifestsBundle }}

    - uses: Azure/k8s-deploy@v1.4
      with:
        action: deploy
        namespace: pipeline-deploy
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          acrhsdemodevops.azurecr.io/restapi:${{ github.sha }}
